---
  title: "Join!"
---

We're always interested in meeting new people who share our interests. Here's how you can join...

# Post-Docs

The lab currently has no funding for post-docs. But I'd be happy to talk to interested folks about other ways of getting funding. NSF post-docs, Field Musuem post-docs and our department's prize post-doc fellowship (the Chamberlin fellowship) are all possibilities. [Get in touch](mailto:gslater@uchicago.edu) to start discussions.

# Grad Students

I'm not currently looking to accept any new graduate students into the lab. However, I do serve on committes for students with other primary advisors and am always happy to chat to prospective students about paleobiology and evolutionary biology at UofC.

I advise students through my home department, [The Department of the Geophysical Sciences](https://geosci.uchicago.edu), [The Committee on Evolutionary Biology](https://evbio.uchicago.edu), and through the graduate program in [Integrative Biology](https://biosciences.uchicago.edu/programs/integrative-biology) at the University of Chicago. [Get in touch](mailto:gslater@uchicago.edu) if you'd like to discuss grad school applications.

# Undergraduate Students

We're always excited to provide research opportunities for undergrads - [Get in touch](mailto:gslater@uchicago.edu) if you're interested in learning more.

